# Generated by Django 4.1.2 on 2022-10-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='Test',
        ),
    ]
